-- stg слой: нормализованные текущие данные (последняя успешная парсинг-версия)

CREATE TABLE IF NOT EXISTS stg.listings (
    listing_id          BIGINT         PRIMARY KEY,
    category            TEXT,
    deal_type           TEXT,
    property_type       TEXT,
    price_kzt           NUMERIC(14,2),
    currency            TEXT           DEFAULT 'KZT',
    rooms               SMALLINT,
    area_total_m2       NUMERIC(8,2),
    area_living_m2      NUMERIC(8,2),
    area_kitchen_m2     NUMERIC(8,2),
    floor               SMALLINT,
    floors_total        SMALLINT,
    building_type       TEXT,
    build_year          SMALLINT,
    ceiling_height_m    NUMERIC(3,2),
    bathroom            TEXT,
    furniture           TEXT,
    renovation          TEXT,
    balcony             TEXT,
    parking             TEXT,
    city_id             INT,
    city_name           TEXT,
    district_name       TEXT,
    address_text        TEXT,
    complex_name        TEXT,
    lat                 NUMERIC(9,6),
    lon                 NUMERIC(9,6),
    description         TEXT,
    description_hash    BYTEA,
    photos_count        INT,
    photos_urls         TEXT[],
    seller_type         TEXT,
    seller_name         TEXT,
    posted_at           TIMESTAMPTZ,
    status              TEXT,
    url                 TEXT,
    source_fetched_at   TIMESTAMPTZ    NOT NULL,
    updated_at          TIMESTAMPTZ    NOT NULL DEFAULT now()
);
